parameters:
- name: ServerName
  type: string
- name: IncludeNative
  type: boolean
- name: DependsOn
  type: object

jobs:
- deployment: PublishPyPI
  displayName: "Publish to PyPI"
  dependsOn: ${{ parameters.DependsOn }}
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  templateContext:
    type: releaseJob
    isProduction: true
    inputs:
    - input: pipelineArtifact
      artifactName: packages_pypi
      targetPath: $(Pipeline.Workspace)/drop
  environment: package-publish
  timeoutInMinutes: 120
  pool:
    name: azsdk-pool
    image: ubuntu-24.04
    os: linux
  strategy:
    runOnce:
      deploy:
        steps:
        - pwsh: |
            $esrpDirectory = "$(Pipeline.Workspace)/esrp-release/${{ parameters.ServerName }}"
            New-Item -ItemType Directory -Force -Path $esrpDirectory
            Get-ChildItem -Path "$(Pipeline.Workspace)/drop/${{ parameters.ServerName }}" `
              | Where-Object { ($_.Name -like "*.tar.gz" -or $_.Name -like "*.whl") } `
              | Copy-Item -Destination $esrpDirectory
            Get-ChildItem $esrpDirectory
          displayName: Isolate files for ESRP Publish

        - task: EsrpRelease@9
          displayName: 'Publish to ESRP'
          inputs:
            ConnectedServiceName: 'Azure SDK PME Managed Identity'
            ClientId: '5f81938c-2544-4f1f-9251-dd9de5b8a81b'
            DomainTenantId: '975f013f-7f24-47e8-a7d3-abc4752bf346'
            UseManagedIdentity: true
            KeyVaultName: 'kv-azuresdk-codesign'
            SignCertName: 'azure-sdk-esrp-release-certificate'
            Intent: 'PackageDistribution'
            ContentType: 'PyPI'
            FolderLocation: $(Pipeline.Workspace)/esrp-release/${{ parameters.ServerName }}
            Owners: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
            Approvers: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
            ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
            MainPublisher: 'ESRPRELPACMANTEST'

        - ${{ if eq(parameters.IncludeNative, true) }}:
          - pwsh: |
              $esrpDirectory = "$(Pipeline.Workspace)/esrp-release/${{ parameters.ServerName }}-native"
              New-Item -ItemType Directory -Force -Path $esrpDirectory
              Get-ChildItem -Path "$(Pipeline.Workspace)/drop/${{ parameters.ServerName }}-native" `
                | Where-Object { ($_.Name -like "*.tar.gz" -or $_.Name -like "*.whl") } `
                | Copy-Item -Destination $esrpDirectory
              Get-ChildItem $esrpDirectory
            displayName: Isolate native files for ESRP Publish

          - task: EsrpRelease@9
            displayName: 'Publish native package to ESRP'
            inputs:
              ConnectedServiceName: 'Azure SDK PME Managed Identity'
              ClientId: '5f81938c-2544-4f1f-9251-dd9de5b8a81b'
              DomainTenantId: '975f013f-7f24-47e8-a7d3-abc4752bf346'
              UseManagedIdentity: true
              KeyVaultName: 'kv-azuresdk-codesign'
              SignCertName: 'azure-sdk-esrp-release-certificate'
              Intent: 'PackageDistribution'
              ContentType: 'PyPI'
              FolderLocation: $(Pipeline.Workspace)/esrp-release/${{ parameters.ServerName }}-native
              Owners: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
              Approvers: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
              ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
              MainPublisher: 'ESRPRELPACMANTEST'