// Generated by AI (UnitTest MCP)
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Net;
using System.Text.Json;
using Azure.Mcp.Core.Services.Azure.Subscription;
using Azure.Mcp.Tools.Storage.Commands;
using Azure.Mcp.Tools.Storage.Commands.Disk;
using Azure.Mcp.Tools.Storage.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Mcp.Tests.Client;
using NSubstitute;
using NSubstitute.ExceptionExtensions;
using Xunit;

namespace Azure.Mcp.Tools.Storage.Tests.Disk;

public class DiskDiagnoseCommandTests : CommandUnitTestsBase<DiskDiagnoseCommand, IStorageIntelligenceService>
{
    private const string DiskResourceId = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/disks/test-disk";
    private const string VmResourceId = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm";
    private const string VmssVmResourceId = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachineScaleSets/test-vmss/virtualMachines/0";
    private const string Subscription = "00000000-0000-0000-0000-000000000001";
    private readonly ISubscriptionResolver _subscriptionResolver;

    public DiskDiagnoseCommandTests()
    {
        _subscriptionResolver = Substitute.For<ISubscriptionResolver>();
        _subscriptionResolver.ResolveSubscription(Arg.Any<string?>()).Returns(call => call.Arg<string?>());
        Services.AddSingleton(_subscriptionResolver);
    }

    [Fact]
    public void Constructor_InitializesCommandCorrectly()
    {
        var command = Command.GetCommand();

        Assert.Equal("diagnose", command.Name);
        Assert.NotNull(command.Description);
        Assert.NotEmpty(command.Description);
    }

    [Theory]
    [InlineData(VmResourceId)]
    [InlineData(VmssVmResourceId)]
    [InlineData(DiskResourceId)]
    public async Task ExecuteAsync_ValidResource_ReturnsAnalysis(string resourceId)
    {
        _subscriptionResolver.ResolveSubscription(null).Returns(Subscription);
        var analysis = CreateJsonElement("""{"status":"Healthy","summary":"No throttling detected."}""");
        Service.DiagnoseDiskAsync(
                Arg.Is(resourceId),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string[]?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<CancellationToken>())
            .Returns(analysis);

        var response = await ExecuteCommandAsync(
            "--resource-id", resourceId);

        var result = ValidateAndDeserializeResponse(
            response,
            StorageJsonContext.Default.DiskDiagnoseCommandResult);
        Assert.Equal("Healthy", result.Analysis.GetProperty("status").GetString());
        Assert.Equal("No throttling detected.", result.Analysis.GetProperty("summary").GetString());
        _subscriptionResolver.DidNotReceive().ResolveSubscription(Arg.Any<string?>());
    }

    [Fact]
    public async Task ExecuteAsync_WithOptionalInputs_ForwardsValues()
    {
        const string startTime = "2026-07-19T00:00:00Z";
        const string endTime = "2026-07-19T12:00:00Z";
        Service.DiagnoseDiskAsync(
                Arg.Any<string>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string[]?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<CancellationToken>())
            .Returns(CreateJsonElement("""{"status":"Healthy"}"""));

        var response = await ExecuteCommandAsync(
            "--resource-id", VmResourceId,
            "--disk", "test-disk",
            "--start-time", startTime,
            "--end-time", endTime);

        Assert.Equal(HttpStatusCode.OK, response.Status);
        await Service.Received(1).DiagnoseDiskAsync(
            VmResourceId,
            null,
            null,
            null,
            Arg.Is<string[]?>(values => values != null && values.SequenceEqual(new[] { "test-disk" })),
            startTime,
            endTime,
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task ExecuteAsync_FriendlySelectorUsesResolvedSubscription()
    {
        _subscriptionResolver.ResolveSubscription(null).Returns(Subscription);
        Service.DiagnoseDiskAsync(
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string[]?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<CancellationToken>())
            .Returns(CreateJsonElement("""{"status":"Healthy"}"""));

        var response = await ExecuteCommandAsync(
            "--resource-group", "test-rg",
            "--vm", "test-vm",
            "--disk", "test-disk");

        Assert.Equal(HttpStatusCode.OK, response.Status);
        await Service.Received(1).DiagnoseDiskAsync(
            null,
            Subscription,
            "test-rg",
            "test-vm",
            Arg.Is<string[]?>(values => values != null && values.SequenceEqual(new[] { "test-disk" })),
            null,
            null,
            Arg.Any<CancellationToken>());
    }

    [Theory]
    [InlineData("", "resource-group")]
    [InlineData("--resource-id not-an-arm-id", "valid Azure resource ID")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Storage/storageAccounts/account", "Microsoft.Compute")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm --resource-group test-rg --vm test-vm", "not both")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/disks/test-disk --disk test-disk", "virtual machine")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm --subscription sub123", "only used")]
    [InlineData("--resource-group test-rg --vm test-vm", "subscription")]
    [InlineData("--subscription sub123 --resource-group invalid/rg --vm test-vm", "resource group")]
    [InlineData("--subscription sub123 --resource-group test-rg --vm invalid/vm", "virtual machine name")]
    [InlineData("--subscription sub123 --resource-group test-rg --vm test-vm --disk invalid.disk", "managed disk name")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm --start-time invalid", "ISO 8601")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm --start-time 2026-07-20T12:00:00Z --end-time 2026-07-20T11:00:00Z", "must be after")]
    [InlineData("--resource-id /subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm --start-time 2026-07-19T00:00:00Z --end-time 2026-07-20T01:00:00Z", "cannot exceed 24 hours")]
    public async Task ExecuteAsync_InvalidInput_ReturnsBadRequest(string args, string expectedMessage)
    {
        var response = await ExecuteCommandAsync(args);

        Assert.Equal(HttpStatusCode.BadRequest, response.Status);
        Assert.Contains(expectedMessage, response.Message, StringComparison.OrdinalIgnoreCase);
        await Service.DidNotReceiveWithAnyArgs().DiagnoseDiskAsync(
            default, default, default, default, default, default, default, TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task ExecuteAsync_FriendlySelectorAllowsPeriodInVmName()
    {
        Service.DiagnoseDiskAsync(
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string[]?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<CancellationToken>())
            .Returns(CreateJsonElement("""{"status":"Healthy"}"""));

        var response = await ExecuteCommandAsync(
            "--subscription", Subscription,
            "--resource-group", "test-rg",
            "--vm", "test.vm");

        Assert.Equal(HttpStatusCode.OK, response.Status);
    }

    [Fact]
    public async Task ExecuteAsync_OversizedResourceId_ReturnsBadRequest()
    {
        var oversizedResourceId = "/subscriptions/" + new string('a', 2048);

        var response = await ExecuteCommandAsync(
            "--resource-id", oversizedResourceId);

        Assert.Equal(HttpStatusCode.BadRequest, response.Status);
        Assert.Contains("cannot exceed 2048 characters", response.Message);
        await Service.DidNotReceiveWithAnyArgs().DiagnoseDiskAsync(
            default, default, default, default, default, default, default, TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task ExecuteAsync_ServiceFailure_ReturnsInternalServerError()
    {
        Service.DiagnoseDiskAsync(
                Arg.Any<string>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<string[]?>(),
                Arg.Any<string?>(),
                Arg.Any<string?>(),
                Arg.Any<CancellationToken>())
            .ThrowsAsync(new Exception("Analysis unavailable"));

        var response = await ExecuteCommandAsync(
            "--resource-id", VmResourceId);

        Assert.Equal(HttpStatusCode.InternalServerError, response.Status);
        Assert.Contains("Analysis unavailable", response.Message);
        Assert.Contains("troubleshooting", response.Message);
    }

    private static JsonElement CreateJsonElement(string json)
    {
        using var document = JsonDocument.Parse(json);
        return document.RootElement.Clone();
    }
}
