<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <!-- Enable strongly typed binding for IConfiguration to support AOT and trimming. -->
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <UserSecretsId>f8ab031a-6160-4218-b776-51a5b6fe2d17</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\ToolDescriptionEvaluator\src\Models\*.cs" Link="Models\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Identity.Broker" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" />
    <PackageReference Include="Microsoft.Azure.Kusto.Ingest" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\queries\GetAvailableTools.kql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
