parameters:
- name: DependsOn
  type: object

jobs:
- job: CreateDockerArtifact
  displayName: 'Creating Docker artifact'
  dependsOn: ${{ parameters.DependsOn }}
  pool:
    name: $(LINUXPOOL)
    image: $(LINUXVMIMAGE)
    os: linux

  steps:
  - checkout: self

  - download: current
    displayName: Download build_info
    artifact: build_info

  - download: current
    displayName: Download binaries_signed
    artifact: binaries_signed

  - task: Powershell@2
    displayName: "Prepare files for Docker"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Prepare-Docker.ps1
      arguments: >
        -ArtifactsPath '$(Pipeline.Workspace)/binaries_signed'
        -BuildInfoPath '$(Pipeline.Workspace)/build_info/build_info.json'
        -OutputPath '$(Build.ArtifactStagingDirectory)'

  - task: 1ES.PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)
      artifact: docker_staged
