parameters:
- name: DependsOn
  type: object

jobs:
- job: PackNpm
  displayName: "Pack Npm"
  dependsOn: ${{ parameters.DependsOn }}
  timeoutInMinutes: 120
  steps:
  - checkout: self

  - download: current
    displayName: Download build_info
    artifact: build_info

  - download: current
    displayName: Download binaries_signed
    artifact: binaries_signed

  - task: Powershell@2
    displayName: "Pack modules for Npm"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Pack-Npm.ps1
      arguments: >
        -BuildInfoPath '$(Pipeline.Workspace)/build_info/build_info.json'
        -ArtifactsPath '$(Pipeline.Workspace)/binaries_signed'
        -OutputPath '$(Build.ArtifactStagingDirectory)'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: packages_npm
