parameters:
- name: PublishTarget
  type: string
  values: [ none, internal, public ]
  default: 'none'
- name: IncludeNative
  type: boolean
  default: true
- name: TestTimeoutInMinutes
  displayName: Test Timeout In Minutes
  type: number
  default: 30

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    ServerName: Azure.Mcp.Server
    PublishTarget: ${{ parameters.PublishTarget }}
    RunLiveTests: true
    PackageDocker: true
    PackageVSIX: true
    PackagePyPI: true
    PackageMCPB: true
    IncludeNative: ${{ parameters.IncludeNative }}
    TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
