// Generated by AI (UnitTest MCP)
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Azure.Mcp.Tools.Storage.Services;
using Xunit;

namespace Azure.Mcp.Tools.Storage.Tests.Services;

public class AttachedDiskResolverTests
{
    private const string OsDiskId = "/subscriptions/sub/resourceGroups/vm-rg/providers/Microsoft.Compute/disks/os-disk";
    private const string DataDiskId = "/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/data-disk";

    private static readonly (string? Name, string? ResourceId)[] s_attachedDisks =
    [
        ("os-disk", OsDiskId),
        ("data-disk", DataDiskId)
    ];

    [Fact]
    public void ResolveResourceIds_MatchesCaseInsensitivelyAndPreservesOrder()
    {
        var result = AttachedDiskResolver.ResolveResourceIds(
            s_attachedDisks,
            [" DATA-DISK ", "OS-DISK"]);

        Assert.Equal([DataDiskId, OsDiskId], result);
    }

    [Fact]
    public void ResolveResourceIds_DeduplicatesNames()
    {
        var result = AttachedDiskResolver.ResolveResourceIds(
            s_attachedDisks,
            ["data-disk", "DATA-DISK"]);

        Assert.Equal([DataDiskId], result);
    }

    [Fact]
    public void ResolveResourceIds_UnattachedNameThrows()
    {
        var exception = Assert.Throws<ArgumentException>(() =>
            AttachedDiskResolver.ResolveResourceIds(s_attachedDisks, ["missing-disk"]));

        Assert.Contains("missing-disk", exception.Message);
        Assert.Contains("not attached", exception.Message);
    }

    [Fact]
    public void ResolveResourceIds_AttachmentWithoutManagedDiskIdThrows()
    {
        var attachedDisks = new[] { (Name: (string?)"ephemeral-os", ResourceId: (string?)null) };

        var exception = Assert.Throws<ArgumentException>(() =>
            AttachedDiskResolver.ResolveResourceIds(attachedDisks, ["ephemeral-os"]));

        Assert.Contains("ephemeral-os", exception.Message);
    }
}
