// Generated by AI (UnitTest MCP)
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Azure.Core;
using Azure.Mcp.Tools.Storage.Services;
using Microsoft.Mcp.Core.Services.Azure.Authentication;
using NSubstitute;
using Xunit;

namespace Azure.Mcp.Tools.Storage.Tests.Services;

public class StorageServiceDiskDiagnoseTests
{
    private const string EndpointEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_ENDPOINT";
    private const string ScopeEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_SCOPE";
    private const string TenantEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_TENANT_ID";
    private const string ResourceId = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm";
    private const string DefaultStorageIntelligenceEndpoint = "https://storageintelligenceweb.production.portalrp.azure.com/api/Disk/analyze";
    private const string DefaultStorageIntelligenceScope = "a5965d26-227b-4df0-a516-d86aba489cb6/.default";
    private const string StorageIntelligenceEndpoint = "https://storage-intelligence.example.com/api/Disk/analyze";
    private const string StorageIntelligenceScope = "00000000-0000-0000-0000-000000000002/.default";
    private const string StorageIntelligenceTenantId = "00000000-0000-0000-0000-000000000003";

    [Fact]
    public async Task DiagnoseDiskAsync_SendsAuthenticatedRequestAndReturnsAnalysis()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy","recommendations":[]}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, attachedDiskService, tokenCredentialProvider, credential) = CreateService(handler);
        const string diskResourceId = "/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/test-disk";
        attachedDiskService.ResolveDiskNamesAsync(
                ResourceId,
                Arg.Any<string[]>(),
                Arg.Any<CancellationToken>())
            .Returns([diskResourceId]);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            diskNames: ["test-disk"],
            startTime: "2026-07-19T00:00:00Z",
            endTime: "2026-07-19T12:00:00Z",
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("Healthy", result.GetProperty("status").GetString());
        Assert.NotNull(handler.Request);
        Assert.Equal(HttpMethod.Post, handler.Request.Method);
        Assert.Equal(
            StorageIntelligenceEndpoint,
            handler.Request.RequestUri?.AbsoluteUri);
        Assert.Equal(new AuthenticationHeaderValue("Bearer", "test-token"), handler.Request.Headers.Authorization);

        using var requestDocument = JsonDocument.Parse(handler.RequestBody!);
        var requestRoot = requestDocument.RootElement;
        Assert.Equal(ResourceId, requestRoot.GetProperty("resourceId").GetString());
        Assert.Equal(diskResourceId, requestRoot.GetProperty("subResourceIds")[0].GetString());
        Assert.Equal("2026-07-19T00:00:00Z", requestRoot.GetProperty("issueStartTime").GetString());
        Assert.Equal("2026-07-19T12:00:00Z", requestRoot.GetProperty("issueEndTime").GetString());
        Assert.False(requestRoot.TryGetProperty("includeHostLatency", out _));

        await attachedDiskService.DidNotReceiveWithAnyArgs().ResolveFriendlySelectorAsync(
            default!, default!, default!, default, TestContext.Current.CancellationToken);
        await attachedDiskService.Received(1).ResolveDiskNamesAsync(
            ResourceId,
            Arg.Is<string[]>(names => names.SequenceEqual(new[] { "test-disk" })),
            Arg.Any<CancellationToken>());
        await tokenCredentialProvider.Received(1).GetTokenCredentialAsync(
            StorageIntelligenceTenantId,
            Arg.Any<CancellationToken>());
        await credential.Received(1).GetTokenAsync(
            Arg.Is<TokenRequestContext>(context => context.Scopes.SequenceEqual(new[] { StorageIntelligenceScope })),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_NonSuccessResponseThrowsSanitizedException()
    {
        var response = new HttpResponseMessage(HttpStatusCode.Forbidden)
        {
            Content = new StringContent("sensitive backend details test-token")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.Forbidden, exception.Status);
        Assert.Contains("HTTP status 403", exception.Message);
        Assert.DoesNotContain("sensitive backend details", exception.Message);
        Assert.DoesNotContain("test-token", exception.Message);
    }

    [Theory]
    [InlineData("""{"status":"Healthy","additive":{"nested":[1,{"preserved":true},null]},"computeInstanceResourceId":"/current","vmResourceId":"/legacy"}""", JsonValueKind.Object)]
    [InlineData("""[{"nested":true},2,null]""", JsonValueKind.Array)]
    [InlineData("\"value\"", JsonValueKind.String)]
    [InlineData("42", JsonValueKind.Number)]
    [InlineData("true", JsonValueKind.True)]
    [InlineData("null", JsonValueKind.Null)]
    public async Task DiagnoseDiskAsync_ValidJsonRoot_IsPreserved(
        string responseJson,
        JsonValueKind expectedKind)
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StreamContent(new MemoryStream(Encoding.UTF8.GetBytes(responseJson)))
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(expectedKind, result.ValueKind);
        using var expectedDocument = JsonDocument.Parse(responseJson);
        Assert.True(JsonElement.DeepEquals(expectedDocument.RootElement, result));
    }

    [Fact]
    public async Task DiagnoseDiskAsync_AdditiveNestedPropertiesAndResourceIdNamesArePreserved()
    {
        const string responseJson =
            """{"computeInstanceResourceId":"/current","vmResourceId":"/legacy","additive":{"nested":[1,{"preserved":true},null]}}""";
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(responseJson)
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("/current", result.GetProperty("computeInstanceResourceId").GetString());
        Assert.Equal("/legacy", result.GetProperty("vmResourceId").GetString());
        Assert.True(result.GetProperty("additive").GetProperty("nested")[1].GetProperty("preserved").GetBoolean());
        Assert.Equal(JsonValueKind.Null, result.GetProperty("additive").GetProperty("nested")[2].ValueKind);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_LatencyMetricsArePreservedWhenProvided()
    {
        const string responseJson =
            """{"status":"Healthy","latencyMetrics":{"latencyEnabled":true,"highLatencyDetected":false,"perDiskLatency":[]}}""";
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(responseJson)
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        var latencyMetrics = result.GetProperty("latencyMetrics");
        Assert.True(latencyMetrics.GetProperty("latencyEnabled").GetBoolean());
        Assert.False(latencyMetrics.GetProperty("highLatencyDetected").GetBoolean());
        Assert.Empty(latencyMetrics.GetProperty("perDiskLatency").EnumerateArray());
    }

    [Theory]
    [InlineData("")]
    [InlineData(" \r\n\t")]
    [InlineData("""{"incomplete":""")]
    public async Task DiagnoseDiskAsync_InvalidSuccessfulBodyThrowsSanitizedBadGateway(string responseBody)
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(responseBody)
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.BadGateway, exception.Status);
        Assert.Contains("Storage Intelligence disk analysis returned", exception.Message);
        Assert.DoesNotContain("incomplete", exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_DeclaredOversizedBodyThrowsBeforeReading()
    {
        var content = new TrackingHttpContent("""{"sensitive":"backend body"}""");
        content.Headers.ContentLength = StorageIntelligenceService.ProvisionalMaxResponseSizeBytes + 1;
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = content
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.BadGateway, exception.Status);
        Assert.Contains(StorageIntelligenceService.ProvisionalMaxResponseSizeBytes.ToString(), exception.Message);
        Assert.False(content.WasRead);
        Assert.DoesNotContain("sensitive", exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_ChunkedOversizedBodyThrowsBadGateway()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StreamContent(new RepeatingByteStream(
                StorageIntelligenceService.ProvisionalMaxResponseSizeBytes + 1,
                (byte)'{'))
        };
        Assert.Null(response.Content.Headers.ContentLength);
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.BadGateway, exception.Status);
        Assert.Contains(StorageIntelligenceService.ProvisionalMaxResponseSizeBytes.ToString(), exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_ResponseAtExactLimitSucceeds()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StreamContent(new ExactSizeJsonStringStream(
                StorageIntelligenceService.ProvisionalMaxResponseSizeBytes))
        };
        Assert.Null(response.Content.Headers.ContentLength);
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(JsonValueKind.String, result.ValueKind);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_MisleadingLowerContentLengthStillEnforcesActualSize()
    {
        var content = new StreamContent(new RepeatingByteStream(
            StorageIntelligenceService.ProvisionalMaxResponseSizeBytes + 1,
            (byte)'{'));
        content.Headers.ContentLength = 1;
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = content
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.BadGateway, exception.Status);
        Assert.Contains(StorageIntelligenceService.ProvisionalMaxResponseSizeBytes.ToString(), exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_CanceledResponseReadPropagatesCancellation()
    {
        using var cancellationSource = new CancellationTokenSource();
        cancellationSource.Cancel();
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StreamContent(new RepeatingByteStream(1, (byte)'0'))
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: cancellationSource.Token));
    }

    [Theory]
    [InlineData(HttpStatusCode.BadRequest)]
    [InlineData(HttpStatusCode.Unauthorized)]
    [InlineData(HttpStatusCode.Forbidden)]
    [InlineData(HttpStatusCode.NotFound)]
    [InlineData(HttpStatusCode.TooManyRequests)]
    [InlineData(HttpStatusCode.InternalServerError)]
    [InlineData(HttpStatusCode.BadGateway)]
    public async Task DiagnoseDiskAsync_NonSuccessBodyIsNeverReadOrLeaked(HttpStatusCode statusCode)
    {
        var content = new TrackingHttpContent("sensitive backend details test-token");
        var response = new HttpResponseMessage(statusCode)
        {
            Content = content
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)statusCode, exception.Status);
        Assert.False(content.WasRead);
        Assert.DoesNotContain("sensitive backend details", exception.Message);
        Assert.DoesNotContain("test-token", exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_FriendlySelectorConstructsVmResourceId()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy"}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, attachedDiskService, _, _) = CreateService(handler);
        attachedDiskService.ResolveFriendlySelectorAsync(
                "00000000-0000-0000-0000-000000000001",
                "test-rg",
                "test-vm",
                Arg.Any<string[]?>(),
                Arg.Any<CancellationToken>())
            .Returns((ResourceId, ["/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/data-disk"]));

        await service.DiagnoseDiskAsync(
            resourceId: null,
            subscription: "00000000-0000-0000-0000-000000000001",
            resourceGroup: "test-rg",
            vm: "test-vm",
            diskNames: ["data-disk"],
            cancellationToken: TestContext.Current.CancellationToken);

        using var requestDocument = JsonDocument.Parse(handler.RequestBody!);
        Assert.Equal(ResourceId, requestDocument.RootElement.GetProperty("resourceId").GetString());
        Assert.False(requestDocument.RootElement.TryGetProperty("includeHostLatency", out _));
        Assert.Equal(
            "/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/data-disk",
            requestDocument.RootElement.GetProperty("subResourceIds")[0].GetString());
        await attachedDiskService.Received(1).ResolveFriendlySelectorAsync(
            "00000000-0000-0000-0000-000000000001",
            "test-rg",
            "test-vm",
            Arg.Is<string[]?>(names => names != null && names.SequenceEqual(new[] { "data-disk" })),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_WithoutConfiguredTenantUsesRequestTenantContext()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy"}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, tokenCredentialProvider, _) = CreateService(handler, tenant: null);

        await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        await tokenCredentialProvider.Received(1).GetTokenCredentialAsync(
            null,
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_WithoutEndpointOrScopeOverridesUsesProductionDefaults()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy"}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, credential) = CreateService(handler);
        Environment.SetEnvironmentVariable(EndpointEnvironmentVariable, null);
        Environment.SetEnvironmentVariable(ScopeEnvironmentVariable, null);

        await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(DefaultStorageIntelligenceEndpoint, handler.Request?.RequestUri?.AbsoluteUri);
        await credential.Received(1).GetTokenAsync(
            Arg.Is<TokenRequestContext>(context => context.Scopes.SequenceEqual(new[] { DefaultStorageIntelligenceScope })),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_InvalidScopeConfigurationThrows()
    {
        var handler = new RecordingHttpMessageHandler(new HttpResponseMessage(HttpStatusCode.OK));
        var (service, _, _, _) = CreateService(handler);
        Environment.SetEnvironmentVariable(ScopeEnvironmentVariable, "not-an-application-scope");

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Contains(ScopeEnvironmentVariable, exception.Message);
        Assert.Null(handler.Request);
    }

    private static (StorageIntelligenceService Service, IAttachedDiskService AttachedDiskService, IAzureTokenCredentialProvider TokenCredentialProvider, TokenCredential Credential) CreateService(
        HttpMessageHandler handler,
        string? tenant = StorageIntelligenceTenantId)
    {
        Environment.SetEnvironmentVariable(EndpointEnvironmentVariable, StorageIntelligenceEndpoint);
        Environment.SetEnvironmentVariable(ScopeEnvironmentVariable, StorageIntelligenceScope);
        Environment.SetEnvironmentVariable(TenantEnvironmentVariable, tenant);

        var attachedDiskService = Substitute.For<IAttachedDiskService>();
        var tokenCredentialProvider = Substitute.For<IAzureTokenCredentialProvider>();
        var credential = Substitute.For<TokenCredential>();
        credential.GetTokenAsync(Arg.Any<TokenRequestContext>(), Arg.Any<CancellationToken>())
            .Returns(new AccessToken("test-token", DateTimeOffset.UtcNow.AddHours(1)));
        tokenCredentialProvider.GetTokenCredentialAsync(Arg.Any<string?>(), Arg.Any<CancellationToken>())
            .Returns(credential);

        var httpClientFactory = new HttpClientFactoryStub(new HttpClient(handler));
        return (new StorageIntelligenceService(attachedDiskService, tokenCredentialProvider, httpClientFactory), attachedDiskService, tokenCredentialProvider, credential);
    }

    private sealed class RecordingHttpMessageHandler(HttpResponseMessage response) : HttpMessageHandler
    {
        public HttpRequestMessage? Request { get; private set; }

        public string? RequestBody { get; private set; }

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            Request = request;
            RequestBody = request.Content is null
                ? null
                : await request.Content.ReadAsStringAsync(cancellationToken);
            return response;
        }
    }

    private sealed class HttpClientFactoryStub(HttpClient httpClient) : IHttpClientFactory
    {
        public HttpClient CreateClient(string name) => httpClient;
    }

    private sealed class TrackingHttpContent(string content) : HttpContent
    {
        public bool WasRead { get; private set; }

        protected override Task SerializeToStreamAsync(
            Stream stream,
            TransportContext? context)
        {
            WasRead = true;
            var bytes = Encoding.UTF8.GetBytes(content);
            return stream.WriteAsync(bytes).AsTask();
        }

        protected override bool TryComputeLength(out long length)
        {
            length = Encoding.UTF8.GetByteCount(content);
            return true;
        }
    }

    private sealed class RepeatingByteStream(long length, byte value) : Stream
    {
        private long _position;

        public override bool CanRead => true;
        public override bool CanSeek => false;
        public override bool CanWrite => false;
        public override long Length => length;
        public override long Position
        {
            get => _position;
            set => throw new NotSupportedException();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            var bytesToRead = (int)Math.Min(count, length - _position);
            buffer.AsSpan(offset, bytesToRead).Fill(value);
            _position += bytesToRead;
            return bytesToRead;
        }

        public override ValueTask<int> ReadAsync(
            Memory<byte> buffer,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var bytesToRead = (int)Math.Min(buffer.Length, length - _position);
            buffer.Span[..bytesToRead].Fill(value);
            _position += bytesToRead;
            return ValueTask.FromResult(bytesToRead);
        }

        public override void Flush() => throw new NotSupportedException();
        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }

    private sealed class ExactSizeJsonStringStream(long length) : Stream
    {
        private long _position;

        public override bool CanRead => true;
        public override bool CanSeek => false;
        public override bool CanWrite => false;
        public override long Length => length;
        public override long Position
        {
            get => _position;
            set => throw new NotSupportedException();
        }

        public override int Read(byte[] buffer, int offset, int count) =>
            ReadCore(buffer.AsSpan(offset, count));

        public override ValueTask<int> ReadAsync(
            Memory<byte> buffer,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return ValueTask.FromResult(ReadCore(buffer.Span));
        }

        private int ReadCore(Span<byte> buffer)
        {
            var bytesToRead = (int)Math.Min(buffer.Length, length - _position);
            if (bytesToRead == 0)
            {
                return 0;
            }

            buffer[..bytesToRead].Fill((byte)'a');
            if (_position == 0)
            {
                buffer[0] = (byte)'"';
            }
            if (_position + bytesToRead == length)
            {
                buffer[bytesToRead - 1] = (byte)'"';
            }

            _position += bytesToRead;
            return bytesToRead;
        }

        public override void Flush() => throw new NotSupportedException();
        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }
}
