// Generated by AI (UnitTest MCP)
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Net;
using System.Net.Http.Headers;
using System.Text.Json;
using Azure.Core;
using Azure.Mcp.Tools.Storage.Services;
using Microsoft.Mcp.Core.Services.Azure.Authentication;
using NSubstitute;
using Xunit;

namespace Azure.Mcp.Tools.Storage.Tests.Services;

public class StorageServiceDiskDiagnoseTests
{
    private const string EndpointEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_ENDPOINT";
    private const string ScopeEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_SCOPE";
    private const string TenantEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_TENANT_ID";
    private const string ResourceId = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/test-vm";
    private const string StorageIntelligenceEndpoint = "https://storage-intelligence.example.com/api/Disk/analyzeV2";
    private const string StorageIntelligenceScope = "00000000-0000-0000-0000-000000000002/.default";
    private const string StorageIntelligenceTenantId = "00000000-0000-0000-0000-000000000003";

    [Fact]
    public async Task DiagnoseDiskAsync_SendsAuthenticatedRequestAndReturnsAnalysis()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy","recommendations":[]}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, attachedDiskService, tokenCredentialProvider, credential) = CreateService(handler);
        const string diskResourceId = "/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/test-disk";
        attachedDiskService.ResolveDiskNamesAsync(
                ResourceId,
                Arg.Any<string[]>(),
                Arg.Any<CancellationToken>())
            .Returns([diskResourceId]);

        var result = await service.DiagnoseDiskAsync(
            ResourceId,
            diskNames: ["test-disk"],
            startTime: "2026-07-19T00:00:00Z",
            endTime: "2026-07-19T12:00:00Z",
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("Healthy", result.GetProperty("status").GetString());
        Assert.NotNull(handler.Request);
        Assert.Equal(HttpMethod.Post, handler.Request.Method);
        Assert.Equal(
            StorageIntelligenceEndpoint,
            handler.Request.RequestUri?.AbsoluteUri);
        Assert.Equal(new AuthenticationHeaderValue("Bearer", "test-token"), handler.Request.Headers.Authorization);

        using var requestDocument = JsonDocument.Parse(handler.RequestBody!);
        var requestRoot = requestDocument.RootElement;
        Assert.Equal(ResourceId, requestRoot.GetProperty("resourceId").GetString());
        Assert.Equal(diskResourceId, requestRoot.GetProperty("subResourceIds")[0].GetString());
        Assert.Equal("2026-07-19T00:00:00Z", requestRoot.GetProperty("issueStartTime").GetString());
        Assert.Equal("2026-07-19T12:00:00Z", requestRoot.GetProperty("issueEndTime").GetString());

        await attachedDiskService.DidNotReceiveWithAnyArgs().ResolveFriendlySelectorAsync(
            default!, default!, default!, default, TestContext.Current.CancellationToken);
        await attachedDiskService.Received(1).ResolveDiskNamesAsync(
            ResourceId,
            Arg.Is<string[]>(names => names.SequenceEqual(new[] { "test-disk" })),
            Arg.Any<CancellationToken>());
        await tokenCredentialProvider.Received(1).GetTokenCredentialAsync(
            StorageIntelligenceTenantId,
            Arg.Any<CancellationToken>());
        await credential.Received(1).GetTokenAsync(
            Arg.Is<TokenRequestContext>(context => context.Scopes.SequenceEqual(new[] { StorageIntelligenceScope })),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_NonSuccessResponseThrowsSanitizedException()
    {
        var response = new HttpResponseMessage(HttpStatusCode.Forbidden)
        {
            Content = new StringContent("sensitive backend details test-token")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, _, _) = CreateService(handler);

        var exception = await Assert.ThrowsAsync<RequestFailedException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal((int)HttpStatusCode.Forbidden, exception.Status);
        Assert.Contains("HTTP status 403", exception.Message);
        Assert.DoesNotContain("sensitive backend details", exception.Message);
        Assert.DoesNotContain("test-token", exception.Message);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_FriendlySelectorConstructsVmResourceId()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy"}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, attachedDiskService, _, _) = CreateService(handler);
        attachedDiskService.ResolveFriendlySelectorAsync(
                "00000000-0000-0000-0000-000000000001",
                "test-rg",
                "test-vm",
                Arg.Any<string[]?>(),
                Arg.Any<CancellationToken>())
            .Returns((ResourceId, ["/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/data-disk"]));

        await service.DiagnoseDiskAsync(
            resourceId: null,
            subscription: "00000000-0000-0000-0000-000000000001",
            resourceGroup: "test-rg",
            vm: "test-vm",
            diskNames: ["data-disk"],
            cancellationToken: TestContext.Current.CancellationToken);

        using var requestDocument = JsonDocument.Parse(handler.RequestBody!);
        Assert.Equal(ResourceId, requestDocument.RootElement.GetProperty("resourceId").GetString());
        Assert.Equal(
            "/subscriptions/sub/resourceGroups/disk-rg/providers/Microsoft.Compute/disks/data-disk",
            requestDocument.RootElement.GetProperty("subResourceIds")[0].GetString());
        await attachedDiskService.Received(1).ResolveFriendlySelectorAsync(
            "00000000-0000-0000-0000-000000000001",
            "test-rg",
            "test-vm",
            Arg.Is<string[]?>(names => names != null && names.SequenceEqual(new[] { "data-disk" })),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_WithoutConfiguredTenantUsesRequestTenantContext()
    {
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"status":"Healthy"}""")
        };
        var handler = new RecordingHttpMessageHandler(response);
        var (service, _, tokenCredentialProvider, _) = CreateService(handler, tenant: null);

        await service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken);

        await tokenCredentialProvider.Received(1).GetTokenCredentialAsync(
            null,
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task DiagnoseDiskAsync_MissingEndpointConfigurationThrows()
    {
        var handler = new RecordingHttpMessageHandler(new HttpResponseMessage(HttpStatusCode.OK));
        var (service, _, _, _) = CreateService(handler);
        Environment.SetEnvironmentVariable(EndpointEnvironmentVariable, null);

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Contains(EndpointEnvironmentVariable, exception.Message);
        Assert.Null(handler.Request);
    }

    [Fact]
    public async Task DiagnoseDiskAsync_InvalidScopeConfigurationThrows()
    {
        var handler = new RecordingHttpMessageHandler(new HttpResponseMessage(HttpStatusCode.OK));
        var (service, _, _, _) = CreateService(handler);
        Environment.SetEnvironmentVariable(ScopeEnvironmentVariable, "not-an-application-scope");

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => service.DiagnoseDiskAsync(
            ResourceId,
            cancellationToken: TestContext.Current.CancellationToken));

        Assert.Contains(ScopeEnvironmentVariable, exception.Message);
        Assert.Null(handler.Request);
    }

    private static (StorageIntelligenceService Service, IAttachedDiskService AttachedDiskService, IAzureTokenCredentialProvider TokenCredentialProvider, TokenCredential Credential) CreateService(
        HttpMessageHandler handler,
        string? tenant = StorageIntelligenceTenantId)
    {
        Environment.SetEnvironmentVariable(EndpointEnvironmentVariable, StorageIntelligenceEndpoint);
        Environment.SetEnvironmentVariable(ScopeEnvironmentVariable, StorageIntelligenceScope);
        Environment.SetEnvironmentVariable(TenantEnvironmentVariable, tenant);

        var attachedDiskService = Substitute.For<IAttachedDiskService>();
        var tokenCredentialProvider = Substitute.For<IAzureTokenCredentialProvider>();
        var credential = Substitute.For<TokenCredential>();
        credential.GetTokenAsync(Arg.Any<TokenRequestContext>(), Arg.Any<CancellationToken>())
            .Returns(new AccessToken("test-token", DateTimeOffset.UtcNow.AddHours(1)));
        tokenCredentialProvider.GetTokenCredentialAsync(Arg.Any<string?>(), Arg.Any<CancellationToken>())
            .Returns(credential);

        var httpClientFactory = new HttpClientFactoryStub(new HttpClient(handler));
        return (new StorageIntelligenceService(attachedDiskService, tokenCredentialProvider, httpClientFactory), attachedDiskService, tokenCredentialProvider, credential);
    }

    private sealed class RecordingHttpMessageHandler(HttpResponseMessage response) : HttpMessageHandler
    {
        public HttpRequestMessage? Request { get; private set; }

        public string? RequestBody { get; private set; }

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            Request = request;
            RequestBody = request.Content is null
                ? null
                : await request.Content.ReadAsStringAsync(cancellationToken);
            return response;
        }
    }

    private sealed class HttpClientFactoryStub(HttpClient httpClient) : IHttpClientFactory
    {
        public HttpClient CreateClient(string name) => httpClient;
    }
}
