parameters:
- name: PublishTarget
  type: string
  values: [ none, internal, public ]
  default: 'none'

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    ServerName: Template.Mcp.Server
    PublishTarget: ${{ parameters.PublishTarget }}
    RunLiveTests: true
    IncludeDockerRelease : false
    IncludeNative: true
    IsTestPipeline: true
