parameters:
- name: PublishTarget
  type: string
  values: [ none, internal, public ]
  default: 'none'
- name: PackageDocker
  type: boolean
  default: false
- name: PackageVSIX
  type: boolean
  default: false
- name: PackagePyPI
  type: boolean
  default: false
- name: PackageMCPB
  type: boolean
  default: false
- name: IncludeNative
  type: boolean
  default: true
- name: TestTimeoutInMinutes
  displayName: Test Timeout In Minutes
  type: number
  default: 30

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    ServerName: Template.Mcp.Server
    PublishTarget: ${{ parameters.PublishTarget }}
    RunLiveTests: true
    PackageDocker: ${{ parameters.PackageDocker }}
    PackageVSIX: ${{ parameters.PackageVSIX }}
    PackagePyPI: ${{ parameters.PackagePyPI }}
    PackageMCPB: ${{ parameters.PackageMCPB }}
    IncludeNative: ${{ parameters.IncludeNative }}
    TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
    IsTestPipeline: true
