parameters:
- name: PublishTarget
  type: string
  values: [ none, internal, public ]
  default: 'none'
- name: PackageDocker
  type: boolean
  default: false
- name: PackageVSIX
  type: boolean
  default: false
- name: IncludeNative
  type: boolean
  default: true

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    ServerName: Template.Mcp.Server
    PublishTarget: ${{ parameters.PublishTarget }}
    RunLiveTests: true
    PackageDocker: ${{ parameters.PackageDocker }}
    PackageVSIX: ${{ parameters.PackageVSIX }}
    IncludeNative: ${{ parameters.IncludeNative }}
    IsTestPipeline: true
