// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Text.Json.Serialization;
using Fabric.Mcp.Tools.OneLake.Commands.File;
using Fabric.Mcp.Tools.OneLake.Commands.Item;
using Fabric.Mcp.Tools.OneLake.Commands.Security;
using Fabric.Mcp.Tools.OneLake.Commands.Settings;
using Fabric.Mcp.Tools.OneLake.Commands.Shortcut;
using Fabric.Mcp.Tools.OneLake.Commands.Table;
using Fabric.Mcp.Tools.OneLake.Commands.Workspace;

namespace Fabric.Mcp.Tools.OneLake.Models;

[JsonSerializable(typeof(Workspace))]
[JsonSerializable(typeof(WorkspaceProperties))]
[JsonSerializable(typeof(WorkspaceMetadata))]
[JsonSerializable(typeof(OneLakeItem))]
[JsonSerializable(typeof(OneLakeItemMetadata))]
[JsonSerializable(typeof(Lakehouse))]
[JsonSerializable(typeof(OneLakeFileInfo))]
[JsonSerializable(typeof(FileSystemItem))]
[JsonSerializable(typeof(CreateItemRequest))]
[JsonSerializable(typeof(UpdateItemRequest))]
[JsonSerializable(typeof(WorkspacesResponse))]
[JsonSerializable(typeof(ItemsResponse))]
[JsonSerializable(typeof(LakehousesResponse))]
[JsonSerializable(typeof(OneLakeEndpoint))]
[JsonSerializable(typeof(OneLakeEnvironmentEndpoints))]
[JsonSerializable(typeof(OneLakeWorkspaceListCommand.OneLakeWorkspaceListCommandResult))]
[JsonSerializable(typeof(OneLakeItemListCommand.OneLakeItemListCommandResult))]
[JsonSerializable(typeof(OneLakeItemListDfsCommand.OneLakeItemListDfsCommandResult))]
[JsonSerializable(typeof(OneLakeItemDataListCommand.OneLakeItemDataListCommandResult))]
[JsonSerializable(typeof(FileReadCommand.FileReadCommandResult))]
[JsonSerializable(typeof(FileWriteCommand.FileWriteCommandResult))]
[JsonSerializable(typeof(FileDeleteCommand.FileDeleteCommandResult))]
[JsonSerializable(typeof(BlobPutCommand.BlobPutCommandResult))]
[JsonSerializable(typeof(BlobGetCommand.BlobGetCommandResult))]
[JsonSerializable(typeof(BlobDeleteCommand.BlobDeleteCommandResult))]
[JsonSerializable(typeof(BlobListCommand.BlobListCommandResult))]
[JsonSerializable(typeof(PathListCommand.PathListCommandResult))]
[JsonSerializable(typeof(DirectoryCreateCommand.DirectoryCreateCommandResult))]
[JsonSerializable(typeof(DirectoryDeleteCommand.DirectoryDeleteCommandResult))]
[JsonSerializable(typeof(TableConfigGetCommand.TableConfigGetCommandResult))]
[JsonSerializable(typeof(TableListCommand.TableListCommandResult))]
[JsonSerializable(typeof(TableGetCommand.TableGetCommandResult))]
[JsonSerializable(typeof(TableNamespaceGetCommand.TableNamespaceGetCommandResult))]
[JsonSerializable(typeof(TableNamespaceListCommand.TableNamespaceListCommandResult))]
[JsonSerializable(typeof(BlobPutResult))]
[JsonSerializable(typeof(BlobGetResult))]
[JsonSerializable(typeof(BlobDeleteResult))]
[JsonSerializable(typeof(TableConfigurationResult))]
[JsonSerializable(typeof(TableListResult))]
[JsonSerializable(typeof(TableGetResult))]
[JsonSerializable(typeof(TableNamespaceGetResult))]
[JsonSerializable(typeof(TableNamespaceListResult))]
[JsonSerializable(typeof(IEnumerable<Workspace>))]
[JsonSerializable(typeof(IEnumerable<OneLakeItem>))]
[JsonSerializable(typeof(IEnumerable<Lakehouse>))]
[JsonSerializable(typeof(IEnumerable<OneLakeFileInfo>))]
[JsonSerializable(typeof(IEnumerable<FileSystemItem>))]
[JsonSerializable(typeof(List<Workspace>))]
[JsonSerializable(typeof(List<OneLakeItem>))]
[JsonSerializable(typeof(List<Lakehouse>))]
[JsonSerializable(typeof(List<OneLakeFileInfo>))]
[JsonSerializable(typeof(List<FileSystemItem>))]
// Data Access Security types
[JsonSerializable(typeof(DataAccessRole))]
[JsonSerializable(typeof(DataAccessRoleListResponse))]
[JsonSerializable(typeof(DataAccessRolePutRequest))]
[JsonSerializable(typeof(DataAccessRoleMembers))]
[JsonSerializable(typeof(DecisionRule))]
[JsonSerializable(typeof(DecisionRuleScope))]
[JsonSerializable(typeof(List<DecisionRuleScope>))]
[JsonSerializable(typeof(Constraints))]
[JsonSerializable(typeof(ColumnConstraint))]
[JsonSerializable(typeof(RowConstraint))]
[JsonSerializable(typeof(FabricItemMember))]
[JsonSerializable(typeof(MicrosoftEntraMember))]
[JsonSerializable(typeof(DataAccessRoleDeleteCommand.DataAccessRoleDeleteCommandResult))]
[JsonSerializable(typeof(DataAccessRoleGetCommand.DataAccessRoleGetCommandResult))]
[JsonSerializable(typeof(DataAccessRoleCreateOrUpdateCommand.DataAccessRoleCreateOrUpdateCommandResult))]
[JsonSerializable(typeof(DataAccessRoleListCommand.DataAccessRoleListCommandResult))]
// Shortcut types
[JsonSerializable(typeof(OneLakeShortcut))]
[JsonSerializable(typeof(ShortcutTarget))]
[JsonSerializable(typeof(OneLakeShortcutTarget))]
[JsonSerializable(typeof(AdlsGen2ShortcutTarget))]
[JsonSerializable(typeof(AmazonS3ShortcutTarget))]
[JsonSerializable(typeof(GoogleCloudStorageShortcutTarget))]
[JsonSerializable(typeof(DataverseShortcutTarget))]
[JsonSerializable(typeof(S3CompatibleShortcutTarget))]
[JsonSerializable(typeof(ExternalDataShareShortcutTarget))]
[JsonSerializable(typeof(AzureBlobStorageShortcutTarget))]
[JsonSerializable(typeof(OneDriveSharePointShortcutTarget))]
[JsonSerializable(typeof(ShortcutListResponse))]
[JsonSerializable(typeof(BulkCreateShortcutsRequest))]
[JsonSerializable(typeof(CreateShortcutWithTransformRequest))]
[JsonSerializable(typeof(CsvToDeltaTransform))]
[JsonSerializable(typeof(CsvToDeltaTransformProperties))]
[JsonSerializable(typeof(BulkCreateShortcutResponse))]
[JsonSerializable(typeof(CreateShortcutResponse))]
[JsonSerializable(typeof(ShortcutRequestInfo))]
[JsonSerializable(typeof(ShortcutCreateError))]
[JsonSerializable(typeof(ShortcutDeleteCommand.ShortcutDeleteCommandResult))]
[JsonSerializable(typeof(ShortcutResetCacheCommand.ShortcutResetCacheCommandResult))]
[JsonSerializable(typeof(ShortcutGetCommand.ShortcutGetCommandResult))]
[JsonSerializable(typeof(ShortcutListCommand.ShortcutListCommandResult))]
[JsonSerializable(typeof(ShortcutCreateAdlsGen2Command.ShortcutCreateAdlsGen2CommandResult))]
[JsonSerializable(typeof(ShortcutCreateAmazonS3Command.ShortcutCreateAmazonS3CommandResult))]
[JsonSerializable(typeof(ShortcutCreateAzureBlobCommand.ShortcutCreateAzureBlobCommandResult))]
[JsonSerializable(typeof(ShortcutCreateDataverseCommand.ShortcutCreateDataverseCommandResult))]
[JsonSerializable(typeof(ShortcutCreateGcsCommand.ShortcutCreateGcsCommandResult))]
[JsonSerializable(typeof(ShortcutCreateOneDriveSharePointCommand.ShortcutCreateOneDriveSharePointCommandResult))]
[JsonSerializable(typeof(ShortcutCreateOneLakeCommand.ShortcutCreateOneLakeCommandResult))]
[JsonSerializable(typeof(ShortcutCreateS3CompatibleCommand.ShortcutCreateS3CompatibleCommandResult))]
[JsonSerializable(typeof(DiagnosticsModifyCommand.DiagnosticsModifyCommandResult))]
[JsonSerializable(typeof(ImmutabilityPolicyModifyCommand.ImmutabilityPolicyModifyCommandResult))]
// Settings types
[JsonSerializable(typeof(OneLakeSettings))]
[JsonSerializable(typeof(SettingsGetCommand.SettingsGetCommandResult))]
[JsonSerializable(typeof(OneLakeDiagnosticSettings))]
[JsonSerializable(typeof(LakehouseDiagnosticDestination))]
[JsonSerializable(typeof(ItemReferenceById))]
[JsonSerializable(typeof(ImmutabilityPolicy))]
[JsonSerializable(typeof(List<ImmutabilityPolicy>))]
[JsonSerializable(typeof(LifecycleSettings))]
// Long running operation types
[JsonSerializable(typeof(OperationState))]
[JsonSerializable(typeof(OperationError))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, WriteIndented = true)]
internal partial class OneLakeJsonContext : JsonSerializerContext;
