parameters:
- name: ServerName
  type: string
- name: NugetDevFeed
  type: string
  default: 'public/azure-sdk-for-net'

jobs:
- job: PublishNpmToDev
  displayName: "Publish npm packages to dev feed"
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  steps:
  - checkout: self

  - download: current
    displayName: Download packages_npm
    artifact: packages_npm

  - template: /eng/pipelines/templates/steps/publish-to-dev-feed.yml
    parameters:
      PathToArtifacts: $(Pipeline.Workspace)/packages_npm
      Registry: https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-js/npm/registry/
      ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'IndividualCI')) }}:
        Tag: dev
      ${{ else }}:
        Tag: pre

- job: PublishNugetToDev
  displayName: "Publish NuGet packages to dev feed"
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  steps:
  - checkout: self

  - download: current
    displayName: Download packages_nuget_signed
    artifact: packages_nuget_signed

  - task: 1ES.PublishNuget@1
    displayName: Publish platform-specific Nugets
    inputs:
      packageParentPath: '$(Pipeline.Workspace)'
      packagesToPush: '$(Pipeline.Workspace)/packages_nuget_signed/${{ parameters.ServerName }}/platform/*.nupkg;!$(Pipeline.Workspace)/packages_nuget_signed/${{ parameters.ServerName }}/platform/*.symbols.nupkg'
      publishVstsFeed: ${{ parameters.NugetDevFeed }}

  - task: 1ES.PublishNuget@1
    displayName: Publish wrapper Nuget
    inputs:
      packageParentPath: '$(Pipeline.Workspace)'
      packagesToPush: '$(Pipeline.Workspace)/packages_nuget_signed/${{ parameters.ServerName }}/wrapper/*.nupkg;!$(Pipeline.Workspace)/packages_nuget_signed/${{ parameters.ServerName }}/wrapper/*.symbols.nupkg'
      publishVstsFeed: ${{ parameters.NugetDevFeed }}

# - job: PublishDocsToNightly
#   displayName: "Update Package Versions"
#   condition: and(succeeded(), or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal'))))
#   dependsOn: PublishDev
#   steps:
#   - checkout: self
#   TODO: Add the steps to publish the docs
