jobs:
- job: PublishSymbols
  displayName: "Publish symbols"
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  timeoutInMinutes: 120
  pool:
    # Symbols conversion tool only runs on Windows
    name: $(WINDOWSPOOL)
    image: $(WINDOWSVMIMAGE)
    os: windows

  steps:
  - checkout: azure-sdk-build-tools

  - download: current
    displayName: Download build_info
    artifact: build_info

  - download: current
    displayName: Download binaries_signed
    artifact: binaries_signed

  - pwsh: |
      $toolPath = "$(Build.SourcesDirectory)/tools/symboltool/pdb2pdb.exe"
      $parent = Split-Path -Path $toolPath -Parent
      Get-ChildItem -Path $parent | Out-Host
      Write-Host "TestPath $toolPath`: $(Test-Path -Path $toolPath)"
    displayName: 'Pdb2Pdb tool directory listing'

  - template: /pipelines/steps/publish-symbols.yml@azure-sdk-build-tools
    parameters:
      BuildToolsRepositoryPath: $(Build.SourcesDirectory)
      PackagesPath: $(Pipeline.Workspace)/binaries_signed
      StagingDirectory: $(Build.ArtifactStagingDirectory)

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: symbols_published
