parameters:
- name: ServerName
  type: string
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: Verify_Signing
  displayName: "Verify Signing"
  pool:
    name: $(WINDOWSPOOL) # Signing verification must happen on windows
    image: $(WINDOWSVMIMAGE)
    os: windows
  variables:
  - template: /eng/pipelines/templates/variables/image.yml
  - template: /eng/pipelines/templates/variables/globals.yml
  steps:
  - checkout: none

  - task: DownloadPipelineArtifact@2
    displayName: Download signed MCP server binaries from specific run
    inputs:
      buildType: specific
      project: $(System.TeamProject)
      pipeline: $(System.DefinitionId) # or a literal ID if different pipeline
      runVersion: specific # required to honor runId
      runId: 5435900
      artifact: binaries_signed
      path: $(Build.ArtifactStagingDirectory)

  - pwsh: |
      Write-Host "Verifying binary signing for win-x64 and win-arm64 binaries..."
      $allSigned = $true
      $signedBinaries = Get-ChildItem -Path '$(Build.ArtifactStagingDirectory)/binaries_signed/**/win-*' -Recurse -Include @("*.dll", "*.exe")
      foreach ($binary in $signedBinaries) {
          if ((Get-AuthenticodeSignature -FilePath $binary.FullName).Status -ne 'Valid') {
              Write-Host "Binary $($binary.FullName) is NOT signed correctly."
              $allSigned = $false
          }
          else {
              Write-Host "Binary $($binary.FullName) is signed correctly."
          }
      }
      if (-not $allSigned) {
          Write-Error "One or more binaries are not signed correctly."
          exit 1
      }
    displayName: "Verify Binary Signing"

- template: /eng/pipelines/templates/jobs/docker/pack-docker.yml
  parameters:
    ServerName: ${{ parameters.ServerName }}