parameters:
- name: ServerName
  type: string
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: Checkout
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  pool:
    name: $(MACPOOL)
    vmImage: $(MACVMIMAGE)
    os: macos
  steps:
  - checkout: self

- template: /eng/pipelines/templates/jobs/docker/pack-docker.yml
  parameters:
    DependsOn: Checkout
    ServerName: ${{ parameters.ServerName }}