parameters:
- name: ServerName
  type: string
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: SignAndPack
  displayName: "Sign and Pack"
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  pool: # Binary signing of mac bits needs to happen on mac see https://github.com/Azure/azure-mcp/blob/4ff032fafc77bc618738879b7028665c0de2e632/eng/scripts/Compress-ForSigning.ps1#L40
    name: $(MACPOOL)
    vmImage: $(MACVMIMAGE)
    os: macos
  steps:
  - checkout: self

  - download: current
    displayName: Download artifacts

  - task: Powershell@2
    displayName: "Compress packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Compress-ForSigning.ps1
      arguments: >
        -ArtifactsPath '$(Pipeline.Workspace)'
        -ArtifactPrefix '$(PipelineArtifactName)_'
        -OutputPath '$(Build.ArtifactStagingDirectory)/signed'

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-230012' # MS Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed
      BinaryPattern: |
        **/win-*/**/azmcp.dll
        **/win-*/**/azmcp.exe
        **/win-*/**/*.Mcp.*.dll

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-231522' # MS 3rd Party Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed
      BinaryPattern: |
        **/win-*/**/ModelContextProtocol*.dll
        **/win-*/**/Npgsql.dll
        **/win-*/**/OpenAI.dll
        **/win-*/**/OpenTelemetry*.dll
        **/win-*/**/YamlDotNet.dll

  - template: pipelines/steps/azd-cli-mac-signing.yml@azure-sdk-build-tools
    parameters:
      MacPath: $(Build.ArtifactStagingDirectory)/signed
      MacPattern: "**/*.zip"

  - task: Powershell@2
    displayName: "Expand packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Expand-AfterSigning.ps1
      arguments: >
        -Path '$(Build.ArtifactStagingDirectory)/signed'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/signed
      ArtifactName: $(PipelineArtifactName)_signed
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

  - task: Powershell@2
    displayName: "Pack modules"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Pack-Modules.ps1
      arguments: >
        -ArtifactsPath '$(Build.ArtifactStagingDirectory)/signed'
        -OutputPath '$(Build.ArtifactStagingDirectory)/packed'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/packed
      ArtifactName: $(PipelineArtifactName)_packed
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
