parameters:
- name: ServerName
  type: string
- name: DependsOn
  type: object
- name: VsixTargets
  type: object
  default:
    - linux-x64
    - linux-arm64
    - macos-x64
    - macos-arm64
    - windows-x64
    - windows-arm64


jobs:
# Deployment Jobs: Publish VSIX artifacts to Marketplace for each vsix target
- ${{ each VsixTarget in parameters.VsixTargets }}:
  - deployment: PublishVSIX_${{ replace(VsixTarget, '-', '_') }}
    displayName: "Publish VSIX Artifact to Marketplace - ${{ VsixTarget }}"
    dependsOn: ${{ parameters.DependsOn }}
    condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
    templateContext:
      type: releaseJob
      isProduction: true
      inputs:
      - input: pipelineArtifact
        artifactName: packages_vsix_signed
        targetPath: $(Pipeline.Workspace)/drop
      - input: pipelineArtifact
        artifactName: build_info
        targetPath: $(Pipeline.Workspace)/build_info
    environment: package-publish
    pool:
      name: azsdk-pool
      image: ubuntu-24.04
      os: linux
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: "Publish (using vsce) - ${{ VsixTarget }}"
            inputs:
              azureSubscription: azure-sdk-vsmarketplace
              scriptType: pscore
              scriptLocation: inlineScript
              workingDirectory: $(Pipeline.Workspace)/drop/${{ parameters.ServerName }}/${{ VsixTarget }}
              inlineScript: |
                Write-Host "Publishing VSIX for ${{ VsixTarget }}"
                Write-Host "VS Code Marketplace info for az login:"
                az rest -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me --resource 499b84ac-1321-427f-aa17-267ca6975798

                $buildInfo = Get-Content "$(Pipeline.Workspace)/build_info/build_info.json" -Raw | ConvertFrom-Json
                $server = $buildInfo.servers | Where-Object { $_.name -eq '${{ parameters.ServerName }}' }

                $baseName = Get-ChildItem *.vsix | Select-Object -ExpandProperty BaseName -First 1

                $args = @('--azure-credential', "--packagePath `"$baseName.vsix`"", "--manifestPath `"$baseName.manifest`"", "--signaturePath `"$baseName.signature.p7s`"")
                if ($server.vsixIsPrerelease) {
                    $args += '--pre-release'
                }

                $publishCmd = "vsce publish $($args -join ' ')"

                Write-Host @"
                Server: $($server.name)
                Version: $($server.version)
                VSIX Version: $($server.vsixVersion)
                VSIX baseName: $baseName
                Is Prerelease: $($server.vsixIsPrerelease)

                Publish arguments:
                  $($args -join '`n  ')
                "@

                Write-Host ''
                Write-Host 'Installing vsce...'
                npm install -g @vscode/vsce

                Write-Host "Executing: $publishCmd"
                Invoke-Expression $publishCmd
