// Generated by AI (UnitTest MCP)
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// cspell:ignore VMRESOURCEID

using System.Text.Json;
using Microsoft.Mcp.Tests;
using Microsoft.Mcp.Tests.Client;
using Microsoft.Mcp.Tests.Client.Helpers;
using Microsoft.Mcp.Tests.Generated.Models;
using Microsoft.Mcp.Tests.Helpers;
using Xunit;

namespace Azure.Mcp.Tools.Storage.Tests;

[Trait("Command", "DiskDiagnoseCommand")]
public class StorageDiskCommandTests(
    ITestOutputHelper output,
    TestProxyFixture fixture,
    LiveServerFixture liveServerFixture)
    : RecordedCommandTestsBase(output, fixture, liveServerFixture)
{
    private const string EmptyGuid = "00000000-0000-0000-0000-000000000000";
    private const string EndpointEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_ENDPOINT";
    private const string ScopeEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_SCOPE";
    private const string TenantEnvironmentVariable = "AZURE_MCP_STORAGE_INTELLIGENCE_TENANT_ID";

    protected override async ValueTask LoadSettingsAsync()
    {
        await base.LoadSettingsAsync();

        if (TestMode == TestMode.Playback)
        {
            Settings.EnvironmentVariables[EndpointEnvironmentVariable] =
                "https://storageintelligenceweb.canary.production.portalrp.azure.com/api/Disk/analyze";
            Settings.EnvironmentVariables[ScopeEnvironmentVariable] =
                "00000000-0000-0000-0000-000000000000/.default";
        }
        else
        {
            Settings.EnvironmentVariables[EndpointEnvironmentVariable] =
                GetRequiredEnvironmentVariable(EndpointEnvironmentVariable);
            Settings.EnvironmentVariables[ScopeEnvironmentVariable] =
                GetRequiredEnvironmentVariable(ScopeEnvironmentVariable);
        }

        Settings.EnvironmentVariables[TenantEnvironmentVariable] = Settings.TenantId;
    }

    public override List<BodyKeySanitizer> BodyKeySanitizers =>
    [
        .. base.BodyKeySanitizers,
        new(new("$..traceId") { Value = "Sanitized" }),
        new(new("$..MaxTimestamp") { Value = "2026-01-01T00:00:00Z" }),
        new(new("$..queryStart") { Value = "2026-01-01T00:00:00Z" }),
        new(new("$..queryEnd") { Value = "2026-01-02T00:00:00Z" })
    ];

    public override List<GeneralRegexSanitizer> GeneralRegexSanitizers =>
    [
        .. base.GeneralRegexSanitizers,
        new(new() { Regex = Settings.SubscriptionId, Value = EmptyGuid }),
        new(new() { Regex = Settings.ResourceGroupName, Value = "Sanitized" }),
        new(new() { Regex = Settings.ResourceBaseName, Value = "Sanitized" })
    ];

    [Fact]
    public async Task Should_diagnose_virtual_machine_disks_by_resource_id()
    {
        var vmResourceId = TestMode == TestMode.Playback
            ? "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Sanitized/providers/Microsoft.Compute/virtualMachines/Sanitized"
            : Settings.DeploymentOutputs["VMRESOURCEID"];

        var result = await CallToolAsync(
            "storage_disk_diagnose",
            new()
            {
                { "resource-id", vmResourceId }
            });

        var analysis = result.AssertProperty("analysis");
        Assert.Equal(JsonValueKind.Object, analysis.ValueKind);

        var status = analysis.AssertProperty("status");
        Assert.False(string.IsNullOrWhiteSpace(status.GetString()));

        var summary = analysis.AssertProperty("summary");
        Assert.False(string.IsNullOrWhiteSpace(summary.GetString()));

        var analyzedVmResourceId = analysis.AssertProperty("vmResourceId");
        Assert.False(string.IsNullOrWhiteSpace(analyzedVmResourceId.GetString()));

        var diskInfo = analysis.AssertProperty("diskInfo");
        Assert.True(diskInfo.AssertProperty("success").GetBoolean());

        var recommendations = analysis.AssertProperty("recommendations");
        Assert.True(recommendations.AssertProperty("success").GetBoolean());
    }

    private static string GetRequiredEnvironmentVariable(string name) =>
        Environment.GetEnvironmentVariable(name) is { Length: > 0 } value
            ? value
            : throw new InvalidOperationException(
                $"Set {name} before running Storage disk diagnosis tests in Record or Live mode.");
}